on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: write

env:
  HAIKU_ARCH: x86_64

jobs:
  build_cross_tools:
    runs-on: ubuntu-latest
    steps:
      - name: Check latest Haiku buildtools btrev
        id: get_btrev
        run: |
          echo "btrev=btrev$(git ls-remote --tags https://review.haiku-os.org/buildtools "btrev*" | sed -e 's:.*refs/tags/btrev::g' | sort -nr | head -n1)" >> "$GITHUB_OUTPUT"
      - name: Check latest buildtools release
        id: get_buildtools
        run: |
          btrev=""
          pageNum=1
          releaseUrl="${{ github.repository }}/releases/tag/buildtools-${{ env.HAIKU_ARCH }}-"
          while [ "$btrev" == "" ];
          do
            # Fetch using GitHub API
            json=$(curl -s ${{ github.api_url }}/repos/${{ github.repository }}/releases?page=$pageNum)
            pageNum=$((pageNum + 1))
            if [ $(echo $json | jq length) -eq 0 ]; then
              # This means that we've passed the end and reached an empty array
              break
            fi
            # Store array of revisions
            revisions=($(echo $json | jq -e -r ".[] | .html_url | select(contains(\"buildtools\"))[${#releaseUrl}:]")) \
              || continue
            btrev=${revisions[0]}
          done
          echo "btrev=$btrev" >> "$GITHUB_OUTPUT"
      - name: Build buildtools
        if: steps.get_btrev.outputs.btrev != steps.get_buildtools.outputs.btrev
        run: |
          echo "Building buildtools at ${{ steps.get_btrev.outputs.btrev }}"
          git clone https://review.haiku-os.org/haiku --depth 1
          git clone https://review.haiku-os.org/buildtools --depth 1
          sudo apt install -y git nasm bc autoconf automake texinfo flex bison gawk build-essential unzip wget zip less zlib1g-dev libzstd-dev xorriso libtool python3 attr
          cd haiku
          mkdir generated.${{ env.HAIKU_ARCH }}; cd generated.${{ env.HAIKU_ARCH }}
          ../configure --cross-tools-source ../../buildtools --build-cross-tools ${{ env.HAIKU_ARCH }} -j$(nproc)
          cd cross-tools-${{ env.HAIKU_ARCH }}
          zip -r ../../../x86_64-linux-buildtools-${{ env.HAIKU_ARCH }}-${{ steps.get_btrev.outputs.btrev }}.zip *
      - name: Upload artifacts
        if: steps.get_btrev.outputs.btrev != steps.get_buildtools.outputs.btrev
        uses: actions/upload-artifact@v3
        with:
          name: x86_64-linux-buildtools-${{ env.HAIKU_ARCH }}-${{ steps.get_btrev.outputs.btrev }}
          path: x86_64-linux-buildtools-${{ env.HAIKU_ARCH }}-${{ steps.get_btrev.outputs.btrev }}.zip
      - name: Create release
        if: steps.get_btrev.outputs.btrev != steps.get_buildtools.outputs.btrev
        id: create-release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: buildtools-${{ env.HAIKU_ARCH }}-${{ steps.get_btrev.outputs.btrev }}
          prerelease: false
          title: Cross compiler for ${{ env.HAIKU_ARCH }} Haiku ${{ steps.get_btrev.outputs.btrev }}
          files: x86_64-linux-buildtools-${{ env.HAIKU_ARCH }}-${{ steps.get_btrev.outputs.btrev }}.zip
